/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pcr' at '1/22/18 3:54 PM' with Gradle 2.14.1
 *
 * @author pcr, @date 1/22/18 3:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
